name: tailwind-traders-products

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: [ 'src/TailwindTraders.Api.Products/**', 'src/TailwindTraders.Api.Core/**' ]

env:
  WEBAPP_NAME: tailwind-traders-products

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: install dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: dotnet publish
      run: dotnet publish -o ../Publish/TailwindTraders.Api.Products -c release
      working-directory: src/TailwindTraders.Api.Products
    - name: azure login
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.TAILWINDTRADERS_TESTING_SERVICEPRINCIPAL }}
    - name: diagnostic output
      run: ls -la ./src/Publish/TailwindTraders.Api.Products
    - name: deploy to app service
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}
        package: ./src/Publish/TailwindTraders.Api.Products
