name: tailwind-traders-website

on:
  workflow_dispatch:
  push:
    branches: [ 'master' ]
    paths: [ 'src/TailwindTraders.Ui.Website/**' ]

env:
  STORAGE_ACCOUNT_NAME: tailwindtradersui2
  CDN_PROFILE_NAME: tailwind-traders-cdn
  CDN_ENDPOINT_NAME: tailwind-traders-ui2
  CDN_RESOURCE_GROUP_NAME: tailwind-traders-rg

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: npm install
      run: npm install
      working-directory: src/TailwindTraders.Ui.Website
    - name: npm run build
      run: npm run build
      working-directory: src/TailwindTraders.Ui.Website
    - name: azure login
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.TAILWINDTRADERS_TESTING_SERVICEPRINCIPAL }}
    - name: deploy to storage
      uses: azure/CLI@v1
      with:
        inlineScript: az storage blob sync --account-name '${{ env.STORAGE_ACCOUNT_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}' -c '$web' -s 'src/TailwindTraders.Ui.Website/build'
    - name: purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: az cdn endpoint purge --no-wait --content-paths '/*' -n '${{ env.CDN_ENDPOINT_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}' -g '${{ env.CDN_RESOURCE_GROUP_NAME }}' --profile-name '${{ env.CDN_PROFILE_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}'
